### ISSUE TITLE
Error instantiating servlet class org.glassfish.jersey.servlet.ServletContainer

### ISSUE THREAD

**Issue by leonardocintra** [livrowebservices/1ed#1]
Esta dando esse erro no capitulo 7!
:-1: 

![image](https://cloud.githubusercontent.com/assets/5832193/10833408/c32e1296-7e78-11e5-90fb-55d7381ad229.png)

**Comment by leonardocintra** [comment]
Para corrigir o erro basta fazer isso: :+1: 

![image](https://cloud.githubusercontent.com/assets/5832193/10833951/a3827046-7e7c-11e5-922d-43c2c84903e3.png)


Fonte: http://stackoverflow.com/questions/8444107/classnotfoundexception-when-starting-tomcat

**Comment by guuilp** [comment]
Resolveu aqui. Obrigado Leonardo!

**Comment by leonardocintra-luizalabs** [comment]
de nada @guuilp

**Comment by FabianoPrazeres** [comment]
Na classe CarroTest no código da página 79, não esta executando, esta aparecendo uma exceção na linha da busca no banco de dados para confirmar se o carro foi salvo, alguém sabe o que pode ser?

**Comment by Vanderlucio** [comment]
Boa tarde, estou com dificuldade em encontrar o erro ao executar o tópico 6.5 do livro esta dando erro no servidor

**Comment by leonardocintra** [comment]
@Vanderlucio poderia explicar melhor ? Como faz muito tempo vou encerrar essa issue, sugiro que abre uma nova apara ajudarmos, para nao confundir assuntos
